### ISSUE TITLE
Inactive server and error message

### ISSUE THREAD

**Issue by veke** [gimm/gulp-live-server#2]
If the started server is inactive for a while, you get error message to console and the process stops. (yet the server is still open). Something to do with the live-reload..? (error points to connect)
events.js:85
throw er; // Unhandled 'error' event
^
Error: listen EADDRINUSE
at exports._errnoException (util.js:746:11)
at Server._listen2 (net.js:1129:14)
at listen (net.js:1155:10)
at Server.listen (net.js:1240:5)
at Function.app.listen (/node_modules/gulp-live-server/node_modules/connect/lib/proto.js:188:24)
at Object. (/node_modules/gulp-live-server/scripts/static.js:16:5)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)

A quick googling says the Error: listen EADDRINUSE means the port is already taken by some other process? That can't be...

**Comment by gimm** [comment]
@vennamo I'm not a heavy user of `gulp-live-server` yet, just used the `static` server a little bit, didn't get your problem, and I couldn't reproduce it with `new` as well.
As `Error: listen EADDRINUSE` states, there's definitely a server running already.
I'm keep an eye on this later on.
Thanks for your feedback!

**Comment by veke** [comment]
There was actually another gulp watch task running ... so yes, there was another process running ... maybe the livereload port should be configurable?

You should also consider to include connect history api fallback to default server settings. 
https://github.com/bripkens/connect-history-api-fallback

**Comment by gimm** [comment]
The live reload port is configurable, see API desc for `gls`.

**Comment by veke** [comment]
aah yes. Must be something wrong with my eyes. :D
